version: "3.9"
services:
  realsense_ros:
    build:
      context: .
      dockerfile: Dockerfile
      #target: librealsense
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
     - ROBOT_IP=192.168.3.96
    network_mode: "host"
